version: "3.8"

services:
  aggregator:
    build: ./Aggregator
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - app-network

  babyapi:
    build: ./BabyAPI
    ports:
      - "5001:5000"
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - app-network

  loader:
    build: ./Loader
    ports:
      - "5002:5000"
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - app-network

  parser:
    build: ./Parser
    ports:
      - "5003:5000"
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - app-network

  nodeapp:
    build: ./NodeApp
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    depends_on:
      - babyapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
